name: DeploytoAWSwithTerraform

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write

jobs:
  deploy-iac:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ secrets.PRODUCTION_EKS_CLUSTER }}
      ECR_REPO_URI: ${{ secrets.ECR_REPO_URI }}

    steps:
      # =========================
      # Checkout Source Code
      # =========================
      - name: Checkout repository
        uses: actions/checkout@v4

      # =========================
      # Install AWS CLI
      # =========================
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version

      # =========================
      # Configure AWS Credentials
      # =========================
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # =========================
      # Setup Terraform
      # =========================
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # =========================
      # Initialize Terraform
      # =========================
      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: terraform-plan
        run: |
          terraform plan -out=tfplan -lock-timeout=5m
          echo "plan_status=success" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        if: steps.terraform-plan.outputs.plan_status == 'success'
        run: terraform apply -lock-timeout=5m tfplan

      - name: Force unlock on failure
        if: failure()
        run: |
          aws dynamodb delete-item \
            --table-name terraform-locks \
            --key "LockID={S='novatrust-terraform-state/env/terraform.tfstate'}" \
            --region ${{ env.AWS_REGION }}

      - name: Install kubectl
